name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Add Key to Clone Private Repos
      uses: ./
      with:
        ssh-private-key: ${{ secrets.FRACDIFF_DEPLOYKEY }}
      run: |
        sh-add -l
        echo SSH_AUTH_SOCK is at $SSH_AUTH_SOCK     
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        flake8 --ignore=F401
